
name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean:clean resources:resources compiler:compile resources:testResources compiler:testCompile surefire:test war:war install:install --file pom.xml 
    - name: Publish WAR file
      run: mkdir staging && cp target/*.war staging
    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: WarFile
        path: staging
